import pool from './database'
import { User, JobInfo, PersonalInfo } from './types'

export class DatabaseService {
  // Authenticate user by employee ID
  static async authenticateByEmployeeId(employeeId: string): Promise<{
    user: User
    jobInfo: JobInfo
    personalInfo?: PersonalInfo
    userType: 'agent' | 'internal' | 'client'
  } | null> {
    try {
      // First, find the job_info record by employee_id
      const jobInfoQuery = `
        SELECT * FROM job_info 
        WHERE employee_id = $1
      `
      const jobInfoResult = await pool.query(jobInfoQuery, [employeeId])
      
      if (jobInfoResult.rows.length === 0) {
        return null
      }

      const jobInfo = jobInfoResult.rows[0] as JobInfo
      let userId: number
      let userType: 'agent' | 'internal' | 'client'

      // Determine user type and get user ID
      if (jobInfo.agent_user_id) {
        userId = jobInfo.agent_user_id
        userType = 'agent'
      } else if (jobInfo.internal_user_id) {
        userId = jobInfo.internal_user_id
        userType = 'internal'
      } else {
        // If neither agent nor internal user ID is found, this is not a valid user for this system
        return null
      }

      // Get user information
      const userQuery = `
        SELECT * FROM users 
        WHERE id = $1
      `
      const userResult = await pool.query(userQuery, [userId])
      
      if (userResult.rows.length === 0) {
        return null
      }

      const user = userResult.rows[0] as User

      // Get personal info
      const personalInfoQuery = `
        SELECT * FROM personal_info 
        WHERE user_id = $1
      `
      const personalInfoResult = await pool.query(personalInfoQuery, [userId])
      const personalInfo = personalInfoResult.rows.length > 0 ? personalInfoResult.rows[0] as PersonalInfo : undefined

      return {
        user,
        jobInfo,
        personalInfo,
        userType
      }
    } catch (error) {
      console.error('Authentication error:', error)
      return null
    }
  }

  // Get user by ID
  static async getUserById(userId: number): Promise<User | null> {
    try {
      const query = 'SELECT * FROM users WHERE id = $1'
      const result = await pool.query(query, [userId])
      return result.rows.length > 0 ? result.rows[0] as User : null
    } catch (error) {
      console.error('Get user error:', error)
      return null
    }
  }

  // Get user's tickets
  static async getUserTickets(userId: number) {
    try {
      const query = `
        SELECT t.*, tc.name as category_name
        FROM tickets t
        LEFT JOIN ticket_categories tc ON t.category_id = tc.id
        WHERE t.user_id = $1 
        ORDER BY t.created_at DESC
      `
      const result = await pool.query(query, [userId])
      return result.rows
    } catch (error) {
      console.error('Get user tickets error:', error)
      return []
    }
  }

  // Create a new ticket
  static async createTicket(ticketData: {
    user_id: number
    concern: string
    details?: string
    category_id?: number
    status?: string
    supporting_files?: string[]
    file_count?: number
  }) {
    try {
      // The ticket_id will be auto-generated by the database trigger
      const query = `
        INSERT INTO tickets (user_id, concern, details, category_id, status, supporting_files, file_count)
        VALUES ($1, $2, $3, $4, $5, $6, $7)
        RETURNING *
      `
      const result = await pool.query(query, [
        ticketData.user_id,
        ticketData.concern,
        ticketData.details || '',
        ticketData.category_id,
        ticketData.status || 'For Approval',
        ticketData.supporting_files || [],
        ticketData.file_count || 0
      ])
      
      return result.rows[0]
    } catch (error) {
      console.error('Create ticket error:', error)
      throw error
    }
  }

  // Get all tickets (for agents/admins)
  static async getAllTickets() {
    try {
      const query = `
        SELECT t.*, u.email, pi.first_name, pi.last_name
        FROM tickets t
        JOIN users u ON t.user_id = u.id
        LEFT JOIN personal_info pi ON u.id = pi.user_id
        ORDER BY t.created_at DESC
      `
      const result = await pool.query(query)
      return result.rows
    } catch (error) {
      console.error('Get all tickets error:', error)
      return []
    }
  }

  // Update ticket status
  static async updateTicketStatus(ticketId: string, status: string, resolvedBy?: number) {
    try {
      const query = `
        UPDATE tickets 
        SET status = $1, resolved_by = $2, resolved_at = CASE WHEN $1 = 'Completed' THEN NOW() ELSE NULL END
        WHERE ticket_id = $3
        RETURNING *
      `
      const result = await pool.query(query, [status, resolvedBy, ticketId])
      return result.rows[0]
    } catch (error) {
      console.error('Update ticket status error:', error)
      throw error
    }
  }

  // Delete ticket
  static async deleteTicket(ticketId: string) {
    try {
      const query = `
        DELETE FROM tickets 
        WHERE ticket_id = $1
        RETURNING *
      `
      const result = await pool.query(query, [ticketId])
      return result.rows.length > 0
    } catch (error) {
      console.error('Delete ticket error:', error)
      throw error
    }
  }
} 